### ISSUE TITLE
ERROR:slobsapi.SlobsConnection:_receive_and_dispatch failing.

### ISSUE THREAD

**Issue by wileyjacobs11** [Julian-O/PySLOBS#18]
ERROR:slobsapi.SlobsConnection:_receive_and_dispatch failing.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyslobs/connection.py", line 209, in _receive_and_dispatch
    message = await self._receive_message()
  File "/usr/local/lib/python3.10/site-packages/pyslobs/connection.py", line 197, in _receive_message
    return await loop.run_in_executor(None, self.websocket.receive_message)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyslobs/connection.py", line 65, in receive_message
    raw_message = self.socket.recv()
  File "/usr/local/lib/python3.10/site-packages/websocket/_core.py", line 362, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python3.10/site-packages/websocket/_core.py", line 385, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python3.10/site-packages/websocket/_core.py", line 406, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python3.10/site-packages/websocket/_core.py", line 445, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python3.10/site-packages/websocket/_abnf.py", line 338, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.10/site-packages/websocket/_abnf.py", line 294, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python3.10/site-packages/websocket/_abnf.py", line 373, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/local/lib/python3.10/site-packages/websocket/_core.py", line 529, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python3.10/site-packages/websocket/_socket.py", line 122, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.
Error occurred: Connection to remote host was lost.

**Comment by Julian-O** [comment]
Thanks for your report. I haven't seen this error before. 

Here what I think is happening:

* You are connecting to StreamLabs Desktop running on a different machine to the script. That is supported by the API, but hasn't been exercised by the tests.
* The websocket has failed, for some vague networky reason, and an exception is raised. You will need to reconnect if this happens.
* The library tries to catch this as an OSError, but the `websocket-client` library reraises this as a different exception that is NOT caught.
* The correct behaviour would be to catch this exception, and other WebSocket exceptions, and shut down the connection gracefully.

I hope to get to this in the next week.

**Comment by Julian-O** [comment]
Believed fixed in V2.0.3.

**Comment by wileyjacobs11** [comment]
The following packages are not available from current channels: - pyslobs==2.0.3

**Comment by Julian-O** [comment]
Please provide more details in your bug reports. How are you trying to install it?

When I try, it works fine:

    > pip install pyslobs==2.0.3
    Collecting pyslobs==2.0.3
      Downloading PySLOBS-2.0.3-py3-none-any.whl (33 kB)
    Collecting websocket-client
      Using cached websocket_client-1.5.3-py3-none-any.whl (56 kB)
    Installing collected packages: websocket-client, pyslobs
    Successfully installed pyslobs-2.0.3 websocket-client-1.5.3

**Comment by Julian-O** [comment]
Closed as unreproducible. Feel free to post more info.
